var eventContext={
eventId:"bootstrap",
data:{
bsdata:{
newState:{
"state": "p_s1",
"fsmname":"primary_fsm",
"subFlowInProgress":false,
"resetSubFSMIdx":0,
"primaryFSMStateIdx":-1,
"flowDeviation":false,
"resetPrimaryFSMStartIdx":-1,
"resetPrimaryFSMEndIdx":-1
}
,
vi:"0a9ce4d7-2a8d-4510-9091-251bcb85c678",
ti:"T1",
tp:"5",
rt:56.516,
mui:5,
uilt:31536000,
wtlt:3600,
wslt:604800,
vilt:31536000,
vclt:100,
exlt:31536000,
aslt:3600,
rnlt:3600,
smplscope:"as",
rvlt:120,
startRE:true,
serverTimeStamp:1525441528503,
clientTimeZoneOffset:0,
vg:"1",
rv:85.731,
bootstrapCachingOn:false,
trackableEvtCfgs:{
weblogConfig:{
ruleVarsToTrack:"a",
variables:[
{
key:"a",
scope:"r"
},
{
key:"c",
scope:"r"
},
{
key:"p",
scope:"r"
},
{
key:"t",
scope:"r"
},
{
key:"v",
scope:"r"
}]}},
trackableEventIds:{
100001:{
config:"weblogConfig"},
110000:{
config:"weblogConfig"}
},
updates:[{key:"buttonPrepaidSuppress", strategy:"p",expr:"SN.CustomScript.getButtonSuppression('vha_button_prepaid_service')",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_btnprepaidsup",
mappingindex:0}]
},
{key:"serviceButtonSuppress", strategy:"p",expr:"SN.CustomScript.getButtonSuppression('vha_button_service')",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_btnssup",
mappingindex:0}]
},
{key:"OSDetails", strategy:"o",expr:"SN.CustomScript.getOS()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_os",
mappingindex:0}]
},
{key:"visitCount", strategy:"o",expr:"$getTotalVisitCount()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_nopCount",
mappingindex:0}]
},
{key:"isRepeatVisitor", strategy:"o",expr:"$isRepeatVisitor()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isRepeatVisitor",
mappingindex:0}]
},
{key:"geoISP", strategy:"o",expr:"$geoIsp()|| ''",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_geoisp",
mappingindex:0}]
},
{key:"browserDetails", strategy:"o",expr:"SN.CustomScript.getBrowser()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_browser",
mappingindex:0}]
},
{key:"proRuleSuppressed", strategy:"p",expr:"SN.CustomScript.getProRuleSuppression()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_prosup",
mappingindex:0}]
},
{key:"landingPageCat", strategy:"o",expr:"SN.CustomScript.getLandingPageCat()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_landingPageCat",
mappingindex:0}]
},
{key:"p", strategy:"o",expr:"var a = { ti:unescape(parent.document.title),cp:unescape(parent.document.location.href),re:unescape(parent.document.referrer)}; a;",scope:"r",
rollingcount:0,
mappedvariables:[
]
},
{key:"isMobiPage", strategy:"o",expr:"SN.CustomScript.isMobilePage()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isMobiPage",
mappingindex:0}]
},
{key:"isContactusstaticsprsd", strategy:"p",expr:"SN.CustomScript.getButtonSuppression('button_statc_contactus')",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_cntus_st_sprsd",
mappingindex:0}]
},
{key:"isIntelliResponseTime", strategy:"p",expr:"SN.CustomScript.isIntelliResponseTime()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isIntelliResponseTime",
mappingindex:0}]
},
{key:"buttonPersistentSuppress", strategy:"p",expr:"SN.CustomScript.getButtonSuppression('vha_button_persistent')",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_btnpsup",
mappingindex:0}]
},
{key:"isComplaintsTime", strategy:"p",expr:"SN.CustomScript.isComplaintsTime();",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isComplaintsTime",
mappingindex:0}]
},
{key:"pageName", strategy:"o",expr:"SN.CustomScript.getPageName();",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_pagename",
mappingindex:0}]
},
{key:"t", strategy:"o",expr:"var a = { de:SN.CustomScript.getProductsInCart(),pr:SN.CustomScript.getValueOfProduct(),qt:SN.CustomScript.getItemsCountInCart(),tp:SN.CustomScript.getTotalCartValue(),tp:SN.CustomScript.getTotalCartValue()}; a;",scope:"r",
rollingcount:0,
mappedvariables:[
]
},
{key:"c", strategy:"o",expr:"var a = { c01:SN.CustomScript.getBrand(),c23:SN.CustomScript.getPromotionalCode(),ct:SN.CustomScript.getCustomerForUpgrades(),isIntelliResponseTime:SN.CustomScript.isIntelliResponseTime(),lvp:SN.CustomScript.getLastVisitExitPage(),pf:SN.CustomScript.getMobileProductType(),c15:SN.CustomScript.getPlanInCart(),srt:SN.CustomScript.getPriceRange(),pcap:SN.CustomScript.getProductCapacity(),pcol:SN.CustomScript.getProductColor(),rpln:SN.CustomScript.getRecommendationPlan(),vut:SN.CustomScript.getVhaUserType()}; a;",scope:"r",
rollingcount:0,
mappedvariables:[
]
},
{key:"initialReferrer", strategy:"o",expr:"SN.CustomScript.getInitialReferrer()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_initialReferrer",
mappingindex:0}]
},
{key:"currentPageUrl", strategy:"o",expr:"unescape(parent.document.location.href)",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_currentPageUrl",
mappingindex:0}]
},
{key:"isContactUsTestPage", strategy:"p",expr:"SN.CustomScript.isContactTestPage()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_iscontact_testpage",
mappingindex:0}]
},
{key:"vhaUserType", strategy:"o",expr:"SN.CustomScript.getVhaUserType()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_vhaUserType",
mappingindex:0}]
},
{key:"buttonSuppress", strategy:"p",expr:"SN.CustomScript.getButtonSuppression('vha_button_1')",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_btnsup",
mappingindex:0}]
},
{key:"intelli_button_suppressed", strategy:"p",expr:"SN.CustomScript.getButtonSuppression('button_intelliresponse')",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_intelli_btn_sprsd",
mappingindex:0}]
},
{key:"activeSessionId", strategy:"o",expr:"SN.CustomScript.activeSessionForRule()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_activeSessionForRule",
mappingindex:0}]
},
{key:"isChatDecInCurrSess", strategy:"p",expr:"SN.CustomScript.getChatDeclinedInCurrSession()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_chtDc",
mappingindex:0}]
},
{key:"geoIP", strategy:"o",expr:"$geoIPAddress() || ''",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_geoIp",
mappingindex:0}]
},
{key:"isDeviceMobile", strategy:"o",expr:"SN.CustomScript.isDeviceMobile()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isDeviceMobile",
mappingindex:0}]
},
{key:"loggedInPast", strategy:"p",expr:"SN.CustomScript.IsLoggedInPast()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_loggedInPast",
mappingindex:0}]
},
{key:"isvhabuttonidavailable", strategy:"p",expr:"SN.CustomScript.isVhaBtnIdAvl(\"247chat\");",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isvhabtnidavl",
mappingindex:0}]
},
{key:"isNonAUSupportedPages", strategy:"p",expr:"SN.CustomScript.isNonAUSupportedPages()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isNonAUSupportedPages",
mappingindex:0}]
},
{key:"isPersistentButtonPage", strategy:"o",expr:"SN.CustomScript.isPersistentButtonPage()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_ispbtnpg",
mappingindex:0}]
},
{key:"a", strategy:"o",expr:"var a = { qu:SN.CustomScript.getQueue()}; a;",scope:"r",
rollingcount:0,
mappedvariables:[
]
},
{key:"complaintsPage", strategy:"o",expr:"SN.CustomScript.isVhaComplaintsPage()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isComplaintsPage",
mappingindex:0}]
},
{key:"isTfsOnChat", strategy:"p",expr:"SN.CustomScript.getTfsOnChat()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_tfsOnChat",
mappingindex:0}]
},
{key:"userJourney", strategy:"o",expr:"SN.CustomScript.getUserJourney()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_userJourney",
mappingindex:0}]
},
{key:"isIntrDoneInCurrSess", strategy:"p",expr:"SN.CustomScript.getInteractionDoneInCurrSession()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_intDone",
mappingindex:0}]
},
{key:"geoCountry", strategy:"o",expr:"SN.CustomScript.getGeoCountry()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_geoCountry",
mappingindex:0}]
},
{key:"geoCity", strategy:"o",expr:"$geoCity() || ''",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_geoCity",
mappingindex:0}]
},
{key:"proactivePageType", strategy:"o",expr:"SN.CustomScript.proactivePageType()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_proactivePageType",
mappingindex:0}]
},
{key:"isRechargingPrepaidService", strategy:"o",expr:"(function(){\
	var regex = /^(.*?(\\bquestion\\=Recharging\\+your\\+prepaid\\+service\\b)[^$]*)$/i;\
    var url = unescape(parent.document.location.href);\
    return regex.test(url)?1:0;\
})();",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isRechargingPrepaidService",
mappingindex:0}]
},
{key:"lastexitvisitpagecategoryinsession", strategy:"o",expr:"SN.CustomScript.getExitPageVisitCategoryInSession()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_lastpagevisit_pc",
mappingindex:0}]
},
{key:"retailSupportPageVariable", strategy:"p",expr:"SN.CustomScript.isVhaRetailSupportPage()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isVhaRetailSupportPage",
mappingindex:0}]
},
{key:"deviceType", strategy:"o",expr:"SN.CustomScript.getDeviceType()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_deviceType",
mappingindex:0}]
},
{key:"iscontactusbtnavl", strategy:"o",expr:"SN.CustomScript.isBtnIdAvl(\"247Chatid\");",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_cntus_st_btn_avl",
mappingindex:0}]
},
{key:"v", strategy:"o",expr:"var a = { pb:SN.CustomScript.getPrevConversion(),br:SN.CustomScript.getBrowser(),ct:$geoCity() || '',co:SN.CustomScript.getGeoCountry(),ip:$geoIPAddress() || '',isp:$geoIsp()|| '',org:$geoOrganization() || '',rv:$isRepeatVisitor(),na:unescape(parent.location.pathname),vc:$getTotalVisitCount(),wr:$geoRegion() || ''}; a;",scope:"r",
rollingcount:0,
mappedvariables:[
]
},
{key:"isButtonPage", strategy:"o",expr:"SN.CustomScript.isButtonPage()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_isbtnpg",
mappingindex:0}]
},
{key:"proInvCount", strategy:"p",expr:"SN.CustomScript.getProactiveInviteCount()",scope:"r",
rollingcount:0,
mappedvariables:[
{name:"mv_proInvCount",
mappingindex:0}]
}],
poll:10,
rgid:"vha_ruleg",
geo:{
location:{
"country":"Italy",
"countryCode":"IT",
"region":"Emilia-Romagna",
"city":"Ravenna",
"lat":"44.41749572753906",
"lon":"12.201095581054688",
"metro":"0",
"area":"0",
"tz":"Europe/Rome"},
isp:{
"geoPrivateIp":"10.65.189.248",
"name":"Vodafone Italia",
"ip":"109.115.190.42",
"org":"Vodafone Italia"}},
ruleconfigs:{"vha_button_1":{
handlerConfig:{
handlerType:"EXECUTE_JS",
appId:"chatApp"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_button_1")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_find":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_best_deals":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_checkout":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_button_1_cg":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.handleButtonRule("vha_button_1_cg", "vha_button_1_cg", SN.Utils.getUniqueId());',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_best_deals_cg":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.handleProRule("vha_pro_best_deals_cg", "vha_pro_best_deals_cg", SN.Utils.getUniqueId(),"p");',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_checkout_cg":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.handleProRule("vha_pro_checkout_cg", "vha_pro_checkout_cg", SN.Utils.getUniqueId(),"p");',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_find_cg":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.handleProRule("vha_pro_find_cg", "vha_pro_find_cg", SN.Utils.getUniqueId(),"p");',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_button_persistent":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_button_persistent")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_button_persistent_cg":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.handleButtonRule("vha_button_persistent_cg", "vha_button_persistent_cg", SN.Utils.getUniqueId());',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_home":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_typeAllMob":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_compareMob":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_androidHome":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_mobileInternet":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_tablets":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_windowsPhone":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_typeContractMob":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_extras":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_hotOffers":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iPhoneHome":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_plans":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_cart":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_upgradescart":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_upgradesUserLogin":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_orderPaymentDetails":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_orderPersonalDetails":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_upgradesExtras":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_upgradesHandList":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iPhone5Details":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iPhone5Spec":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsungGalaxy":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsung":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsungMobSpec":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsungMobDet":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_home_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_typeAllMob_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_compareMob_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_androidHome_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_mobileInternet_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_tablets_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_windowsPhone_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_typeContractMob_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_extras_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_hotOffers_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iPhoneHome_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_plans_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_cart_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_upgradescart_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_upgradesUserLogin_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_orderPaymentDetails_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_orderPersonalDetails_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_checkout_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_upgradesExtras_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_upgradesHandList_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iPhone5xPricing":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_mobi":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"invitation"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_pagename":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_mobile":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphone6":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphone6_TP2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_email":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_email_copy":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_Bill_explainer":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_home":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_1":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_3":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_4":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_4_copy":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Button_Service_Rule_2":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_button_service")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Button_Service_Rule_3":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_button_service")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Button_Service_Rule_4":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_button_service")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_button_service":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_button_service")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_5_ContactUs":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_6_BillExplainer":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_7_IntRoaming":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_button_intelli":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("button_intelliresponse")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"button_intelliresponse":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("button_intelliresponse")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"button_statc_contactus":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("button_statc_contactus")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_mobileBroadband":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_repeatVisit":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_MobileHome":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_TabletHome":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_SimOnly":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_RedPlans":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_MobileBB_Plan":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_byo_tablet_modem":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_productPages":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_TabletDetails":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_ActiveSession_RV":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_mnb_desktop":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"invitation"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iPhone_Prodpg_newlaunch":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iPhone_Spec_newlaunch":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_ipad_Spec_newlaunch":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_dock":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_pro_dock")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"button_complaints":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"invitation"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_MNB_DESKTOP_REPEAT":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"invitation"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_MNB_DESKTOP_NEW":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"invitation"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_MNB_DESKTOP_CUSTOMER":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"invitation"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_cart_mnb_sup":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_ckot_mnb_sup":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_ACN":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsung_galaxy_s7":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphone-se":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_htc_one_x9":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_directlink_1_social":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"invitation"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_myvf_bal":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_myvf_dtusg":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_directlink_contact":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"invitation"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphone_spec_landingpage":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphone_product_page":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphone_cart_page":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_track_trace_page":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_service_Rule_myvf_mngmypl":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_button_complaints_page":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_button_complaints_page")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_non_au_ip":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_button_retail_support_page":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_button_retail_support_page")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_prepaid":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_button_prepaid_service":{
handlerConfig:{
handlerType:"EXECUTE_JS"},
stateChangeReq:false,
js:'SN.CustomScript.insertButtonChat("vha_button_prepaid_service")',
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsung_galaxy_s8":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_8_Tracking":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_9_IntRoaming":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_10_IntRoaming":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_11_Retail":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_12_Intelliresponse":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_directlink_retail":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"invitation"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_nbn":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_nbn_copy":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_nbnplans":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_business":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_13_nbnservice":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_14_nbnsupport":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_15_nbntrbshting":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_15_nbnbarred":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_test1":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_test2":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"VHA_Service_Rule_test3":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphone8":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsung_note8":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsung_note8_copy":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphonex":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphonecom":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphonecompare":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_eligibility":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_plansim":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_iphonexcom":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_billing":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_device":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_myvodafone":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_upgrade":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_prepaid":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_signup":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_complaints":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_support_plans":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsungs9":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsungs9com":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]},"vha_pro_samsung_Galaxy_S9":{
handlerConfig:{
handlerType:"START_WOWPX_APP",
appId:"chatApp"},
stateChangeReq:false,
widgetConfigName:"chatInviteWidgetConfig",
params:[
]}}
},
ruledata:{generatedvariables:[
{
key:"gen_time_on_page",
expr:"$timeOnPage()",
strategy:"p",
scope:"r"
}
]
,
rules:{"button_complaints":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_geoIp",
type:'v'
},{
expr:"247",
type:'c'
}]
}]
,
mappedvariables:["mv_geoIp","mv_currentPageUrl"]
},
"button_intelliresponse":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_isIntelliResponseTime",
type:'v'
},{
expr:"1",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_isvhabtnidavl",
type:'v'
},{
expr:"1",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intelli_btn_sprsd",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
mappedvariables:["mv_currentPageUrl","mv_isIntelliResponseTime","mv_isvhabtnidavl","mv_tfsOnChat","mv_intelli_btn_sprsd"]
},
"vha_button_1":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_btnsup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_isbtnpg",
type:'v'
},{
expr:"true",
type:'c'
}]
}]
,
mappedvariables:["mv_btnsup","mv_geoCountry","mv_isbtnpg","mv_tfsOnChat"]
},
"vha_button_complaints_page":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_isComplaintsTime",
type:'v'
},{
expr:"1",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_isvhabtnidavl",
type:'v'
},{
expr:"1",
type:'c'
}]
}]
,
mappedvariables:["mv_isvhabtnidavl","mv_isComplaintsTime","mv_tfsOnChat","mv_isComplaintsPage"]
},
"vha_button_prepaid_service":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_btnprepaidsup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_geoCountry","mv_btnprepaidsup","mv_tfsOnChat"]
},
"vha_button_retail_support_page":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_isvhabtnidavl",
type:'v'
},{
expr:"1",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
mappedvariables:["mv_isVhaRetailSupportPage","mv_isvhabtnidavl","mv_tfsOnChat"]
},
"vha_button_service":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_btnssup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_btnssup","mv_tfsOnChat"]
},
"VHA_Button_Service_Rule_2":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
mappedvariables:["mv_currentPageUrl","mv_tfsOnChat"]
},
"VHA_Button_Service_Rule_3":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
mappedvariables:["mv_currentPageUrl","mv_tfsOnChat"]
},
"VHA_Button_Service_Rule_4":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
mappedvariables:["mv_currentPageUrl","mv_tfsOnChat"]
},
"vha_directlink_1_social":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_geoIp",
type:'v'
},{
expr:"247",
type:'c'
}]
}]
,
mappedvariables:["mv_geoIp"]
},
"vha_directlink_contact":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_geoIp",
type:'v'
},{
expr:"247",
type:'c'
}]
}]
,
mappedvariables:["mv_geoIp","mv_currentPageUrl"]
},
"vha_directlink_retail":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_geoIp",
type:'v'
},{
expr:"247",
type:'c'
}]
}]
,
mappedvariables:["mv_geoIp","mv_currentPageUrl"]
},
"VHA_MNB_DESKTOP_CUSTOMER":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat"]
},
"VHA_MNB_DESKTOP_NEW":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_loggedInPast",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_loggedInPast","mv_deviceType","mv_tfsOnChat"]
},
"VHA_MNB_DESKTOP_REPEAT":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_loggedInPast",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_loggedInPast","mv_deviceType","mv_tfsOnChat"]
},
"vha_pro_ACN":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_business":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:60,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_cart":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_cart_mnb_sup":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_vhaUserType","mv_currentPageUrl","mv_nopCount","mv_geoCountry","mv_geoIp"]
},
"vha_pro_ckot_mnb_sup":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_vhaUserType","mv_nopCount","mv_geoCountry","mv_geoIp"]
},
"vha_pro_eligibility":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_htc_one_x9":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iphone-se":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iphone8":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iphonecom":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iphonecompare":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iphonex":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iphonexcom":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iphone_cart_page":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
}]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iPhone_Prodpg_newlaunch":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iphone_product_page":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_iphone_spec_landingpage":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_nbn":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:60,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_nbnplans":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:60,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_non_au_ip":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:20,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"noteq",
operands:[{
expr:"mv_isVhaRetailSupportPage",
type:'v'
},{
expr:"1",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"noteq",
operands:[{
expr:"mv_isComplaintsPage",
type:'v'
},{
expr:"1",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_isNonAUSupportedPages",
type:'v'
},{
expr:"1",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_geoCountry","mv_geoIp","mv_isVhaRetailSupportPage","mv_isComplaintsPage","mv_isNonAUSupportedPages"]
},
"vha_pro_productPages":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:40,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_samsungs9":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_samsungs9com":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_samsung_galaxy_s7":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_samsung_galaxy_s8":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_samsung_Galaxy_S9":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_samsung_note8":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_SimOnly":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:20,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"vha_pro_support_billing":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"vha_pro_support_device":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"vha_pro_support_myvodafone":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"vha_pro_support_plans":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"vha_pro_support_prepaid":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"vha_pro_support_signup":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"vha_pro_support_upgrade":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"vha_pro_TabletDetails":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:20,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_deviceType",
type:'v'
},{
expr:"D",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"VHA_Service_Rule_10_IntRoaming":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_chtDc","mv_prosup","mv_intDone","mv_geoIp","mv_tfsOnChat"]
},
"VHA_Service_Rule_13_nbnservice":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"VHA_Service_Rule_14_nbnsupport":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"VHA_Service_Rule_15_nbnbarred":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"VHA_Service_Rule_2":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:20,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_chtDc","mv_intDone","mv_prosup","mv_geoIp","mv_tfsOnChat"]
},
"VHA_Service_Rule_3":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:5,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_chtDc","mv_prosup","mv_intDone","mv_geoIp","mv_tfsOnChat"]
},
"VHA_Service_Rule_5_ContactUs":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:5,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_iscontact_testpage",
type:'v'
},{
expr:"false",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_tfsOnChat","mv_currentPageUrl","mv_iscontact_testpage","mv_geoCountry","mv_geoIp"]
},
"VHA_Service_Rule_7_IntRoaming":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:15,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_chtDc","mv_intDone","mv_prosup","mv_geoIp","mv_tfsOnChat"]
},
"VHA_Service_Rule_8_Tracking":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoCountry","mv_geoIp"]
},
"VHA_Service_Rule_9_IntRoaming":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_chtDc","mv_intDone","mv_prosup","mv_geoIp","mv_tfsOnChat"]
},
"VHA_Service_Rule_myvf_bal":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_chtDc","mv_prosup","mv_intDone","mv_geoIp","mv_tfsOnChat"]
},
"VHA_Service_Rule_myvf_dtusg":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_chtDc","mv_prosup","mv_intDone","mv_geoIp","mv_tfsOnChat"]
},
"VHA_service_Rule_myvf_mngmypl":{
preconditions:[
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_currentPageUrl","mv_chtDc","mv_prosup","mv_intDone","mv_geoIp","mv_tfsOnChat"]
},
"VHA_Service_Rule_prepaid":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_isRechargingPrepaidService",
type:'v'
},{
expr:"1",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_geoCountry","mv_isRechargingPrepaidService"]
},
"VHA_Service_Rule_test1":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:60,
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_prosup","mv_intDone","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"VHA_Service_Rule_test2":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:60,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
},
"VHA_Service_Rule_test3":{
preconditions:[
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_prosup",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_tfsOnChat",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"TIMER",
operator:"gteq",
operands:[{
expr:"gen_time_on_page",
type:'v'
},{
expr:30,
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_intDone",
type:'v'
},{
expr:"0",
type:'c'
}]
},
{"type":"VARIABLE",
operator:"eq",
operands:[{
expr:"mv_chtDc",
type:'v'
},{
expr:"0",
type:'c'
}]
}]
,
genvariables:["gen_time_on_page"]
,
mappedvariables:["mv_chtDc","mv_intDone","mv_prosup","mv_deviceType","mv_tfsOnChat","mv_currentPageUrl","mv_geoIp"]
}}
}

}
};
SN.EventManager.fire("pageevent",eventContext);